### ISSUE TITLE
Как исправить данную проблему?

### ISSUE THREAD

**Issue by mdapm9di** [audiz/YandexMusicBot#1]
![image](https://github.com/audiz/YandexMusicBot/assets/108079001/630dd809-826c-4dc8-bfa2-ba931ff9615e)

**Comment by audiz** [comment]
Mainclass location fixed in commit e8f0a2e3eed443a396fb91a3bcbeeda2adabe482

**Comment by audiz** [comment]
обновил страничку с инструкцией

**Comment by audiz** [comment]
Привет, обновил страничку с инструкцией
