### ISSUE TITLE
Почему могут не работать команды?

### ISSUE THREAD

**Issue by mdapm9di** [audiz/YandexMusicBot#2]
Не работают команды плейлистов, дейлика и так же приходит только демка на запрос
![image](https://github.com/audiz/YandexMusicBot/assets/108079001/8802d729-b778-4586-bb85-2a66fce5d2df)

P.S. Я немного ошибся, прошу прощения

**Comment by Maatarashiii** [comment]
Cockie забрал правильно

**Comment by Maatarashiii** [comment]
![image](https://github.com/audiz/YandexMusicBot/assets/108079001/d6fd2e13-33db-494f-b18c-913207f9fdee)
