### ISSUE TITLE
Что насчёт новых функций для бота?

### ISSUE THREAD

**Issue by mdapm9di** [audiz/YandexMusicBot#3]
Добавить кнопку для скачивания всего плейлиста, или всех треков на странице автора, и т.д.

**Comment by audiz** [comment]
Интересная идея, подумаю что можно сделать

**Comment by mdapm9di** [comment]
Ещё предлагаю в начале запуска бота реализовать меню смены языка в боте, для тех кто не хочет лезть в файлы .kt, это будет удобно

**Comment by audiz** [comment]
добавлено в 1560caf24b820a077eadabe90b7146f4e16af04e
